// `.env.ts` is generated by the `npm run env` command
import env from './.env';
import { NgxLoggerLevel } from 'ngx-logger';
import { Language } from 'src/app/core/common/model/language/language.model';

export const environment = {
  production: true,
  company: 'ActiveCitizen',
  version: env.npm_package_version,
  serverUrl: '/api',
  envName: 'PROD',
  API_URL: 'assets/api',
  defaultLanguage: new Language('Ελληνικά', 'el'),
  supportedLanguages: [new Language('Ελληνικά', 'el'), new Language('English', 'en')],
  serverLoggingUrl: '',
  serverLogLevel: NgxLoggerLevel.OFF, // TODO - Change me once server is available
  disableConsoleLogging: true,
  logLevel: NgxLoggerLevel.INFO
};
